# Provider variables
variable "ak" {
  type        = string
  description = "The access key of the FlexibleEngine cloud"
  sensitive   = true
}
variable "sk" {
  type        = string
  description = "The secret key of the FlexibleEngine cloud"
  sensitive   = true
}
variable "db_pass" {
  type        = string
  description = "The password of RDS DB database"
  sensitive   = true
}
variable "domain_name" {
  type        = string
  description = "The Name of the Domain to scope to"
}
variable "tenant_name" {
  type        = string
  description = "The Name of the Project to login with"
}
variable "region" {
  type        = string
  description = "Region of the FlexibleEngine cloud"
}

# VPC and Subnet variables
variable "cidr_vpc" {
  type        = string
  description = "Specifies the VPC CIDR"
}
variable "cidr_subnet_in" {
  type        = string
  description = "Specifies the input subnet CIDR"
}
variable "cidr_subnet_out" {
  type        = string
  description = "Specifies the output subnet CIDR"
}
variable "cidr_subnet_sync" {
  type        = string
  description = "Specifies the Synchronization subnet CIDR"
}

variable "cidr_dmz_vpc" {
  type        = string
  description = "Specifies the DMZ VPC CIDR"
}
variable "cidr_subnet_dmz" {
  type        = string
  description = "Specifies the DMZ subnet CIDR"
}


variable "cidr_private_vpc" {
  type        = string
  description = "Specifies the Private VPC CIDR"
}
variable "cidr_subnet_private" {
  type        = string
  description = "Specifies the Private subnet CIDR"
}


variable "gateway_in" {
  type        = string
  description = "Gateway of the input subnet"
}
variable "gateway_out" {
  type        = string
  description = "Gateway of the output subnet"
}
variable "gateway_sync" {
  type        = string
  description = "Gateway of the synchronization subnet"
}

variable "dmz_gateway" {
  type        = string
  description = "Gateway of the DMZ subnet"
}

variable "private_gateway" {
  type        = string
  description = "Gateway of the private subnet"
}

variable "tag" {
  type        = string
  description = "Tagging resources"
}

# KeyPair Name
variable "generated_key_name" {
  type        = string
  default     = "TF-KeyPair"
  description = "Key-pair generated by Terraform"
}
