# Provider variables
variable "ak" {
  type = string
  description = "The access key of the FlexibleEngine cloud"
  sensitive = true
}
variable "sk" {
  type = string
  description = "The secret key of the FlexibleEngine cloud"
  sensitive = true
}
variable "db_pass" {
  type = string
  description = "The password of RDS DB database"
  sensitive = true
}
variable "mrs_pass" {
  type = string
  description = "The password of MRS cluster manager"
  sensitive = true
}
variable "domain_name" {
  type = string
  description = "The Name of the Domain to scope to"
}
variable "tenant_name" {
  type = string
  description = "The Name of the Project to login with"
}
variable "region" {
  type = string
  description = "Region of the FlexibleEngine cloud"
}
/*
variable "availability_zone_names" {
  type = list(string)
  description = "Availability zone of resource"
  default = ["eu-west-0a","eu-west-0b","eu-west-0c"]
}
*/

# VPC and Subnet variables
variable "cidr_vpc" {
  type = string
  description = "Specifies the VPC CIDR"
}
variable "cidr_subnet_in" {
  type = string
  description = "Specifies the input subnet CIDR"
}
variable "cidr_subnet_out" {
  type = string
  description = "Specifies the output subnet CIDR"
}
variable "cidr_subnet_sync" {
  type = string
  description = "Specifies the Synchronization subnet CIDR"
}

variable "cidr_dmz_vpc" {
  type = string
  description = "Specifies the DMZ VPC CIDR"
}
variable "cidr_subnet_dmz" {
  type = string
  description = "Specifies the DMZ subnet CIDR"
}

variable "cidr_prod_vpc" {
  type = string
  description = "Specifies the production VPC CIDR"
}
variable "cidr_subnet_app" {
  type = string
  description = "Specifies the application subnet CIDR"
}
variable "cidr_subnet_data" {
  type = string
  description = "Specifies the data subnet CIDR"
}

variable "cidr_dev_vpc" {
  type = string
  description = "Specifies the development environment VPC CIDR"
}
variable "cidr_subnet_dev" {
  type = string
  description = "Specifies the development environment subnet CIDR"
}


variable "gateway_in" {
  type = string
  description = "Gateway of the input subnet"
}
variable "gateway_out" {
  type = string
  description = "Gateway of the output subnet"
}
variable "gateway_sync" {
  type = string
  description = "Gateway of the synchronization subnet"
}

variable "dmz_gateway" {
  type = string
  description = "Gateway of the DMZ subnet"
}

variable "app_gateway" {
  type = string
  description = "Gateway of the application subnet"
}
variable "data_gateway" {
  type = string
  description = "Gateway of the data subnet"
}

variable "dev_gateway" {
  type = string
  description = "Gateway of the development subnet"
}

variable "tag" {
  type        = string
  description = "Tagging resources"
}

# KeyPair Name
variable "generated_key_name" {
  type        = string
  default     = "TF-KeyPair"
  description = "Key-pair generated by Terraform"
}